packages:
  - "packages/*"
linkWorkspacePackages: true
preferWorkspacePackages: true
allowBuilds:
  esbuild: true
  nx: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - nx
  - unrs-resolver
